name: models
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.4.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  cloud_firestore: ^4.17.0  
  shared:
    path: ../shared
  cupertino_icons: ^1.0.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1

  flutter_lints: ^3.0.0
