name: blocs
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  injectable: ^2.4.1
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.6
  repositories:
    path: ../repositories
  services:
    path: ../services
  models:
    path: ../models
  shared:
    path: ../shared


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1


  flutter_lints: ^3.0.0
